[package]
name = "os"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
buddy_system_allocator = "0.6"
# polyhal = { git = "https://github.com/Huzhiwen1208/polyhal.git", branch = "feature/libos-sup", features = [
#     "kcontext",
# ] }
polyhal = {path = "/home/jackhu/rust-os/polyhal", features = ["kcontext"]}
cfg-if = "1.0"

[features]
libos = ["polyhal/libos"]

[profile.release]
debug = true
